config/routes.rb
Rails.application.routes.draw do
  root 'flights#index'

  get 	'/flights', 			to: "flights#index"
  get 	'/new_booking', 	to: "bookings#new"
  post 	'/new_booking', 	to: "bookings#create"

  resources :bookings, only: [:show]
end

app/models/airport.rb
class Airport < ApplicationRecord
	has_many :arrivals, class_name: "Flight", foreign_key: "finish_airport_id"
	has_many :departures, class_name: "Flight", foreign_key: "start_airport_id"

	validates :code, presence: true 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
	has_many :booking_passengers
  has_many :passengers, through: :booking_passengers
  
  belongs_to :flight

  accepts_nested_attributes_for :booking_passengers
end

app/models/booking_passenger.rb
class BookingPassenger < ApplicationRecord
  belongs_to :booking
  belongs_to :passenger

  accepts_nested_attributes_for :passenger
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :start_airport, class_name: "Airport"
  belongs_to :finish_airport, class_name: "Airport" 

  has_many :bookings
  has_many :passengers, through: :bookings

  def self.search_flights(date, from_airport, to_airport)
  	where("start_day = ? AND start_airport_id = ? AND finish_airport_id = ?", date, from_airport, to_airport)
  end

  def self.available_dates
  	Flight.all.map { |e| [e.start_day.strftime("%d/%m/%Y"),e.start_day] }.uniq { |e| e.first	}
  end
  
end

app/models/flight_passenger.rb
class FlightPassenger < ApplicationRecord
  belongs_to :flight
  belongs_to :passenger
end

app/models/passenger.rb
class Passenger < ApplicationRecord
	has_many :booking_passengers
	has_many :bookings, through: :booking_passengers

	has_many :flights, through: :bookings

	validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :format_date, :format_time

	def format_date(date)
  	date.to_date.strftime("%d/%m/%Y")
  end

  def format_time(datetime)
  	datetime.strftime("%d/%m/%Y %H:%M %Z")
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
  	@booking = Booking.new
  	@passengers = (params[:passenger_amount].to_i).times { Passenger.new }
    if params[:chosen_flight]
  		@chosen_flight = Flight.find(params[:chosen_flight])
  	end
  end

  def create
		@booking = Booking.new(flight_id: params[:booking][:flight_id], passenger_amount: params[:booking][:passenger_amount])
    i = 0
    while i < (params[:booking][:passenger_amount]).to_i
      @booking.passengers.build(name: params[:booking][:booking_passenger][:passenger][i][:name], email: params[:booking][:booking_passenger][:passenger][i][:email])
      i +=1
    end
		if @booking.save
      i = 0
      while i < (params[:booking][:passenger_amount]).to_i
        PassengerMailer.with(passenger: @booking.passengers[i], booking: @booking).thank_you_email.deliver_later
        i += 1
      end
      flash[:success] = "Booking created!"
      redirect_to @booking
		else
			flash.now[:error] = @booking.errors.full_messages
		end
  end

  def show
    @booking = Booking.find(params[:id])
    @flight = Flight.find(@booking.flight_id)
  end

  private 
    def booking_params
      params.require(:booking).permit(:flight_id, :passenger_amount, booking_passengers_attributes: [passenger_attributes:[:name, :email] ] )
    end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
  	@flights = Flight.all
  	@airports = Airport.all.map { |e| [e.code,e.id]  }
  	@passenger_amount = [["1",1], ["2",2], ["3",3], ["4",4]]
  	@available_dates = Flight.available_dates
  	@booking = Booking.new

  	if params[:date]
  		@flights = Flight.search_flights(params[:date],params[:from_airport], params[:to_airport])
  	else
  		@flights = nil
  	end
  end



  private

  def flight_params
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<h1>Bookings#new</h1>


<% if @chosen_flight %>
	<div class="flight-details">
		From: <%= @chosen_flight.start_airport.code %><br>
		To: <%= @chosen_flight.finish_airport.code %><br>
		Time: <%= @chosen_flight.start_time %><br>
		Duration: <%= @chosen_flight.duration %><br>
		ID: <%= @chosen_flight.id %><br><br>
	</div>


	<h2>Enter the passenger information:</h2>
	<p>
		<%= form_for @booking, url: { action: "create" } do |f| %>
			<%= f.hidden_field :flight_id, value: @chosen_flight.id %>
			<%= f.hidden_field :passenger_amount, value: params[:passenger_amount] %>

			<%= f.fields_for @booking.booking_passengers do |bp| %>

				<% (params[:passenger_amount].to_i).times do %>
					<%= bp.fields_for :passenger, index: bp.index do |pass| %>
						<%= pass.label :name, "Name:" %>
						<%= pass.text_field :name %><br>
						<%= pass.label :email, "Email:" %>
						<%= pass.text_field :email %><br><br>
					<% end %>
				<% end %>
				
			<% end %>
		
		
			<%= f.submit "Book flight" %>

		<% end %>

	</p>

<% end %>

app/views/bookings/show.html.erb
<h1>Booking Details</h1>
<p>
	ID: <%= @booking.id %><br>
	Passenger Amount: <%= @booking.passenger_amount %>
</p>
<h2>Flight Details</h2>
<p>
	To: <%= @flight.start_airport.code %><br>
	From: <%= @flight.finish_airport.code %><br>
	Time: <%= @flight.start_time %><br>
	Duration: <%= @flight.duration %><br>
</p>
<h2>Flight Passengers</h2>
<p>
	<% @flight.passengers.each do |f| %>
		Name: <%= f.name %><br>
		Email: <%= f.email %><br><br>
	<% end %>
</p>

app/views/flights/index.html.erb
<h1>Search Flights</h1>
<div>
	<%= form_tag("/flights", method: "get") do %>
		Date: 	<%= select_tag(:date, options_for_select(@available_dates)) %> <br>
		From: 	<%= select_tag(:from_airport, options_for_select(@airports)) %>
		To: 	<%= select_tag(:to_airport, options_for_select(@airports)) %><br>
		Passengers: <%= select_tag(:passenger_amount, options_for_select(@passenger_amount) )%>
		<br><br><%= submit_tag "Search" %>
	<% end %>
</div>

<div>
	<% if params[:date] %>
		<h2>Flights on <%= format_date(params[:date]) %>, From <%= Airport.find(params[:from_airport]).code %> To <%= Airport.find(params[:to_airport]).code %>, with <%= pluralize(params[:passenger_amount],"passenger") %>
			
		</h2>
		<%= form_for @booking, url: new_booking_path, method: "get" do |f| %>
			<% @flights.each do |f| %>
				<%= radio_button_tag(:chosen_flight, f.id) %>
				<span class="first-span">From: <%= f.start_airport.code %></span> 
				<span>To: <%= f.finish_airport.code %></span>
				<span>Date: <%= format_time(f.start_time) %></span>
				<span>Duration: <%= f.duration %></span><br><br>
			<% end %>
			<%= hidden_field_tag :passenger_amount, params[:passenger_amount] %>

			<%= submit_tag "Choose flight" %>
		<% end %>
	<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |f| %>
      <%= f %>
    <% end %>
    <%= yield %>
    <br><br>
    <%= link_to "Search flights", root_path %>
  </body>
</html>